services:
  mkdocs:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mydocs
    ports:
      - 7070:80
    networks:
      - mkdocs_network

networks:
  mkdocs_network:
    driver: bridge
