# Project information
site_name: My MkDocs Project
site_description: 'An example MkDocs project using the Material theme'
site_url: 'https://freshystar.github.io/mk-docs'  # Change this to your site's URL

# Theme settings
theme:
  name: material

# Navbar settings (site structure)
nav:
  - Home: index.md
  - About: about.md
  - TAAF: multipass.md

# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Repository configuration (for the edit link on pages)
repo_name: freshystar/mk-docs
repo_url: https://github.com/freshystar/mk-docs
edit_uri: edit/master/docs/
